name: subpack_analyzer
description: A sample command-line application.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.8.0

# Add regular dependencies here.
dependencies:
  analyzer: ^8.0.0
  args: ^2.7.0
  dart_console: ^4.1.2
  equatable: ^2.0.7
  fast_immutable_collections: ^11.0.4
  mason_logger: ^0.2.16
  path: ^1.9.1
  very_good_cli: ^0.17.1
  yaml: ^3.1.3

dev_dependencies:
  lints: ^4.0.0
  test: ^1.24.0
