include: package:werkbank_lints/werkbank_lints.yaml

analyzer:
  exclude:
    - lib/src/_internal/src/package_copies/**
    - lib/**/*.*.dart
    - lib/src/localization/**
    - lib/**/*_icons.dart
    - test/**/*.*.dart
  language:
    strict-casts: true
    strict-inference: true
    strict-raw-types: true
