name: werkbank
sdkPath: .fvm/flutter_sdk

packages:
  - apps/*
  - packages/*
  - example/example_werkbank

scripts:
  flutter:pub_get:
    description: Run flutter pub get
    run: dart run melos exec -c 1 -- "flutter pub get"


  dart:format:
    description: Runs the formatter in all packages.
    run: dart run melos exec --  "dart format lib"

  dart:fix:
    description: Fixes all dart lints.
    run: dart run melos exec -- "dart fix --apply"

  index_generator:
    description: Run the index_generator in all packages that require it.
    packageFilters:
      scope:
        - werkbank
    run: |
      cd packages/werkbank &&
      dart run tool/generate_index_generator_yaml.dart &&
      # We need to run the index_generator twice,
      # since it seems to not add exports of index files
      # that it generated itself for the first time.
      dart run index_generator &&
      dart run index_generator

  dart:slang:
    description: Run the slang in all packages that require it.
    packageFilters:
      scope:
        - werkbank
    run: dart run melos exec -- "dart run slang"

  iconfont:generate:
    description: Run the icon_font_genrator.
    packageFilters:
      scope:
        - werkbank
    run: |
      cd packages/werkbank &&
      dart run tool/generate_icon_font.dart
