name: werkbank
sdkPath: .fvm/flutter_sdk

packages:
  - apps/*
  - packages/*
  - example/example_werkbank

scripts:
  flutter:pub_get:
    description: Run flutter pub get
    run: dart run melos exec -c 1 -- "flutter pub get"


  dart:format:
    description: Runs the formatter in all packages.
    run: dart run melos exec --  "dart format lib"

  dart:fix:
    description: Fixes all dart lints.
    run: dart run melos exec -- "dart fix --apply"

  index_generator:
    description: Run the index_generator in all packages that require it.
    packageFilters:
      scope:
        - werkbank
    run: |
      cd packages/werkbank &&
      dart run tool/generate_index_generator_yaml.dart &&
      # We need to run the index_generator twice,
      # since it seems to not add exports of index files
      # that it generated itself for the first time.
      dart run index_generator &&
      dart run index_generator

  slang:
    description: Run the slang in all packages that require it.
    packageFilters:
      scope:
        - werkbank
    run: |
      dart run melos exec -- "dart run slang"
      dart run melos exec -- "dart format lib"

  icon_font_generator:
    description: Run the icon_font_genrator.
    packageFilters:
      scope:
        - werkbank
    run: |
      cd packages/werkbank &&
      dart run tool/generate_icon_font.dart

  subpack_analyzer:
    description: Run the subpack_analyzer in all packages that require it.
    packageFilters:
      scope:
        - werkbank
    run: cd packages/subpack_analyzer &&
      fvm dart run bin/subpack_analyzer.dart run

  subpack_analyzer_verbose:
    description: Run the subpack_analyzer in all packages that require it.
    packageFilters:
      scope:
        - werkbank
    run: cd packages/subpack_analyzer &&
      fvm dart run bin/subpack_analyzer.dart run --verbose

  subpack_analyzer_analysisDirs:
    description: Run the subpack_analyzer in all packages that require it.
    packageFilters:
      scope:
        - werkbank
    run: cd packages/subpack_analyzer &&
      fvm dart run bin/subpack_analyzer.dart run --analysisDirs=tool,example

  subpack_analyzer_analysisDirs_verbose:
    description: Run the subpack_analyzer in all packages that require it.
    packageFilters:
      scope:
        - werkbank
    run: cd packages/subpack_analyzer &&
      fvm dart run bin/subpack_analyzer.dart run --analysisDirs=tool,example --verbose
