import 'package:flutter/material.dart';
import 'package:werkbank/src/addons/src/knobs/src/knobs/interval/named_curve.dart';

const predefinedCurves = <NamedCurve>[
  // Flutter predefined curves
  NamedCurve('linear', 'Flutter', Curves.linear),
  NamedCurve('decelerate', 'Flutter', Curves.decelerate),
  NamedCurve(
    'fastLinearToSlowEaseIn',
    'Flutter',
    Curves.fastLinearToSlowEaseIn,
  ),
  NamedCurve(
    'fastEaseInToSlowEaseOut',
    'Flutter',
    Curves.fastEaseInToSlowEaseOut,
  ),
  NamedCurve('ease', 'Flutter', Curves.ease),
  NamedCurve('easeIn', 'Flutter', Curves.easeIn),
  NamedCurve('easeInToLinear', 'Flutter', Curves.easeInToLinear),
  NamedCurve('easeInSine', 'Flutter', Curves.easeInSine),
  NamedCurve('easeInQuad', 'Flutter', Curves.easeInQuad),
  NamedCurve('easeInCubic', 'Flutter', Curves.easeInCubic),
  NamedCurve('easeInQuart', 'Flutter', Curves.easeInQuart),
  NamedCurve('easeInQuint', 'Flutter', Curves.easeInQuint),
  NamedCurve('easeInExpo', 'Flutter', Curves.easeInExpo),
  NamedCurve('easeInCirc', 'Flutter', Curves.easeInCirc),
  NamedCurve('easeInBack', 'Flutter', Curves.easeInBack),
  NamedCurve('easeOut', 'Flutter', Curves.easeOut),
  NamedCurve('linearToEaseOut', 'Flutter', Curves.linearToEaseOut),
  NamedCurve('easeOutSine', 'Flutter', Curves.easeOutSine),
  NamedCurve('easeOutQuad', 'Flutter', Curves.easeOutQuad),
  NamedCurve('easeOutCubic', 'Flutter', Curves.easeOutCubic),
  NamedCurve('easeOutQuart', 'Flutter', Curves.easeOutQuart),
  NamedCurve('easeOutQuint', 'Flutter', Curves.easeOutQuint),
  NamedCurve('easeOutExpo', 'Flutter', Curves.easeOutExpo),
  NamedCurve('easeOutCirc', 'Flutter', Curves.easeOutCirc),
  NamedCurve('easeOutBack', 'Flutter', Curves.easeOutBack),
  NamedCurve('easeInOut', 'Flutter', Curves.easeInOut),
  NamedCurve('easeInOutSine', 'Flutter', Curves.easeInOutSine),
  NamedCurve('easeInOutQuad', 'Flutter', Curves.easeInOutQuad),
  NamedCurve('easeInOutCubic', 'Flutter', Curves.easeInOutCubic),
  NamedCurve(
    'easeInOutCubicEmphasized',
    'Flutter',
    Curves.easeInOutCubicEmphasized,
  ),
  NamedCurve('easeInOutQuart', 'Flutter', Curves.easeInOutQuart),
  NamedCurve('easeInOutQuint', 'Flutter', Curves.easeInOutQuint),
  NamedCurve('easeInOutExpo', 'Flutter', Curves.easeInOutExpo),
  NamedCurve('easeInOutCirc', 'Flutter', Curves.easeInOutCirc),
  NamedCurve('easeInOutBack', 'Flutter', Curves.easeInOutBack),
  NamedCurve('fastOutSlowIn', 'Flutter', Curves.fastOutSlowIn),
  NamedCurve('slowMiddle', 'Flutter', Curves.slowMiddle),
  NamedCurve('bounceIn', 'Flutter', Curves.bounceIn),
  NamedCurve('bounceOut', 'Flutter', Curves.bounceOut),
  NamedCurve('bounceInOut', 'Flutter', Curves.bounceInOut),
  NamedCurve('elasticIn', 'Flutter', Curves.elasticIn),
  NamedCurve('elasticOut', 'Flutter', Curves.elasticOut),
  NamedCurve('elasticInOut', 'Flutter', Curves.elasticInOut),
  // m3Guidelines
  NamedCurve('emphasizedAccelerate', 'M3', Easing.emphasizedAccelerate),
  NamedCurve('emphasizedDecelerate', 'M3', Easing.emphasizedDecelerate),
  NamedCurve('linear', 'M3', Easing.linear),
  NamedCurve('standard', 'M3', Easing.standard),
  NamedCurve('standardAccelerate', 'M3', Easing.standardAccelerate),
  NamedCurve('standardDecelerate', 'M3', Easing.standardDecelerate),
  NamedCurve('legacyDecelerate', 'M3', Easing.legacyDecelerate),
  NamedCurve('legacyAccelerate', 'M3', Easing.legacyAccelerate),
  NamedCurve('legacy', 'M3', Easing.legacy),
];
